"""add account currency

Revision ID: b31edd4ea603
Revises: c55c56bb7c8a
Create Date: 2026-07-21 22:00:23.311479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b31edd4ea603'
down_revision: Union[str, Sequence[str], None] = 'c55c56bb7c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'accounts',
        sa.Column('currency', sa.String(length=3), nullable=False, server_default='usd'),
    )
    op.alter_column('accounts', 'currency', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'currency')
    # ### end Alembic commands ###
